[project]
name = "aibou"
version = "0.1.0"
description = "Aibou (相棒) is a simple and elegant @groq powered Flask chat interface"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.3",
    "groq>=1.0.0",
]
